### ISSUE TITLE
Is this the right kind of approach?

### ISSUE THREAD

**Issue by benfredwells** [WICG/get-installed-related-apps#1]
From @marcoscaceres on the WICG discourse:

> it worries me that an application is reaching into the OS to get information about installed apps.

and

> I would expect some kind of "request ownership" model (similar to intents today) and some kind of browser or OS provided UI: where the user is given the choice as to where push notifications should be routed (either the native app or the web app - but the user is given the ultimate control)

These are great questions. We could tackle them separately but I think the real question is whether the high level approach of this API is right, or if we should go with something quite different.

A completely different approach might be to do something specific to notifications, and solve it more as an extension to the notifications API. Marcos, is that what you were thinking?

About the security aspects, note that only related native apps can be queried - there would need to be some link created from the web app to the native app, and from the native app to the web app, for this to work. This would require one party to have control of both the web app and native app.

**Comment by rayankans** [comment]
closing since this is obsolete
