### ISSUE TITLE
Expose the native app's version number

### ISSUE THREAD

**Issue by tomayac** [WICG/get-installed-related-apps#10]
For some use cases, it's needed to know the exact version number of a particular app if it is installed.

**Comment by bluepnume** [comment]
We have the same use-case. Different versions of our app support different features, and knowing in advance whether to redirect or not would be greatly beneficial.

**Comment by rayankans** [comment]
I've started drafting the spec, and made it include the version. I also updated the README/EXPLAINER.

This was also implemented on chromium [tracking bug](https://bugs.chromium.org/p/chromium/issues/detail?id=1013568).

Closing the issue, please re-open if you have further concerns
