### ISSUE TITLE
Issue with getInstalledRelatedApps API

### ISSUE THREAD

**Issue by prash-mi** [WICG/get-installed-related-apps#12]
Hi,

I am getting a couple of issues with getInstalledRelatedApps API:

**Issue 1**: The function call `getInstalledRelatedApps` never returns. I have included the meta token and have enabled the #enable-experimental-web-platform-features flag as well. The test code is deployed @ https://mweb-demos.appspot.com/get-related-apps/ and pasting the function here for your reference: 

```
  const callGetInstalledRelatedApps = async () => {
		let listOfInstalledApps = null;
		  try {
			   log('Calling navigator.getInstalledRelatedApps');
			   listOfInstalledApps = await navigator.getInstalledRelatedApps();
		} catch (e) {
			log('Error: '+e);
			return;
		}  
		//listOfInstalledApps must have been resolved by this line
		for (const app of listOfInstalledApps) {
	  // These fields are specified by the Web App Manifest spec.
			  log('platform:', app.platform);
			  log('url:', app.url);
			  log('id:', app.id);
		}
  
  }
```

**Issue 2**: The API throws the error: `TypeError: navigator.getInstalledRelatedApps is not a function` , doublechecked that the origin-trial token is present. Please refer: https://m.economictimes.com/related_apps.cms

Tested on Chrome 77.0.3865.92 and Chrome Canary 79.0.3927.0 both. 
Please let me know of you have any questions.

Regards,
Prashant

**Comment by rayankans** [comment]
If you have an implementation related issue you should file a bug against the browser. In this case crbug.com.

I checked your issues anyway, for Issue 1 it seems to be working but you are getting an empty list. Issue 2 means that you don't have the flag or OT properly set-up.

I'm closing this issue for now. If you ahve further issues please file them against crbug.com.

**Comment by tushar004** [comment]
> Hi,
> 
> I am getting a couple of issues with getInstalledRelatedApps API:
> 
> **Issue 1**: The function call `getInstalledRelatedApps` never returns. I have included the meta token and have enabled the #enable-experimental-web-platform-features flag as well. The test code is deployed @ https://mweb-demos.appspot.com/get-related-apps/ and pasting the function here for your reference:
> 
> ```
>   const callGetInstalledRelatedApps = async () => {
> 		let listOfInstalledApps = null;
> 		  try {
> 			   log('Calling navigator.getInstalledRelatedApps');
> 			   listOfInstalledApps = await navigator.getInstalledRelatedApps();
> 		} catch (e) {
> 			log('Error: '+e);
> 			return;
> 		}  
> 		//listOfInstalledApps must have been resolved by this line
> 		for (const app of listOfInstalledApps) {
> 	  // These fields are specified by the Web App Manifest spec.
> 			  log('platform:', app.platform);
> 			  log('url:', app.url);
> 			  log('id:', app.id);
> 		}
>   
>   }
> ```
> 
> **Issue 2**: The API throws the error: `TypeError: navigator.getInstalledRelatedApps is not a function` , doublechecked that the origin-trial token is present. Please refer: https://m.economictimes.com/related_apps.cms
> 
> Tested on Chrome 77.0.3865.92 and Chrome Canary 79.0.3927.0 both.
> Please let me know of you have any questions.
> 
> Regards,
> Prashant

You can use the below code, it's working.
const fun = navigator['getInstalledRelatedApps'];
listOfInstalledApps = await fun.call(navigator);
