### ISSUE TITLE
Expand on definition of platform and give example

### ISSUE THREAD

**Issue by foolip** [WICG/get-installed-related-apps#20]
From https://wicg.github.io/get-installed-related-apps/spec/#platform and its use in the spec I was unable to guess what kind of string it might be or how to use it, but from the [explainer](https://github.com/WICG/get-installed-related-apps/blob/master/EXPLAINER.md) I gather it's the app store from which the app was installed.

Giving an example of how to use it would be great. Maybe one has to switch on it to guess what form the other fields should be?

Related: https://github.com/WICG/get-installed-related-apps/issues/14

**Comment by rayankans** [comment]
The Manifest spec where `platform` is defined contains examples. Clicking on the definition of `ExternalApplicationResource` will link to that.

> but from the explainer I gather it's the app store from which the app was installed.

Yeah, it's intentionally left vague to give OSes/platforms the flexibility to define them as needed. The way the verification can be applied is platform-specific anyway, so the documentation needs to live elsewhere.

**Comment by foolip** [comment]
I see, so linking to https://www.w3.org/TR/appmanifest/#dom-externalapplicationresource-platform from https://wicg.github.io/get-installed-related-apps/spec/#platform would make it easy to discover what this is.
