### ISSUE TITLE
Describe privacy mitigations

### ISSUE THREAD

**Issue by foolip** [WICG/get-installed-related-apps#24]
On the [blink-dev intent thread](https://groups.google.com/a/chromium.org/d/msg/blink-dev/wB7mDJqrUZ8/gadvToTmBAAJ) the number of related apps to return was limited to 3. The spec need not prescribe this exact number, but it would be good to suggest it in https://wicg.github.io/get-installed-related-apps/spec/index.html#privacy-considerations and add the optional steps that limit the number in the appropriate algorithm. Since the same applications need to be returned every time, presumably a way of sorting has to be added.

**Comment by rayankans** [comment]
I added an optional browser-defined limit. Obtaining the manifest returns the related apps in a deterministic order, so there's no need to define a sorting operation.
