### ISSUE TITLE
API not working with an external JSON on android manifest

### ISSUE THREAD

**Issue by nacho2487** [WICG/get-installed-related-apps#25]
With an external JSON on android manifest using `include`, I couldn't make the API works.  But removing the `include` and paste it inside the the `string` like [the example](https://web.dev/get-installed-related-apps/#relationship-native) it works.

Here is an example that I couldn't make it work:
```
<resources>
<string name="smartlock_asset_statement" translatable="false">
        [{
            \"include\": \"https://example.com/.well-known/assetlinks.json\"
        }]
  </string>
</resources>
```
.well-known/assetlinks.json
```
[
  {
    "relation": [
      "delegate_permission/common.handle_all_urls"
    ],
    "target": {
      "namespace": "web",
      "site": "https://example.com"
    }
  }
]
```
This is the way we communicate between apps and web for sign-in, we follow this [docs](https://developers.google.com/identity/smartlock-passwords/android/associate-apps-and-sites#associate_your_app_with_your_website). We were expecting doing the same with this API.

**Comment by rayankans** [comment]
This seems to be a chromium bug, not a spec issue. Please file a feature request at bugs.chromium.org with the Blink>AppManifest component. Chromium does not currently support DAL include statements.

Closing this issue.

**Comment by rake7h** [comment]
@nacho2487 did you make it work with include DAL? facing same issue.
