### ISSUE TITLE
Sub-domain support?

### ISSUE THREAD

**Issue by RajeshBatth** [WICG/get-installed-related-apps#27]
Is it possible for having sub-domain support?

if my company has multiple domains for multiple products, can we match them all by some pattern like https://*.company.com ?

{
            \"relation\": [\"delegate_permission/common.handle_all_urls\"],
            \"target\": {
              \"namespace\": \"web\",
              \"site\": \"https://*.company.com\"
            }
        }

**Comment by rayankans** [comment]
Hi Rajesh,

This is an implementation detail, and out-of-scope for this repo which is about spec issues. I'd file a bug against crbug.com with this question. Closing the issue.
