### ISSUE TITLE
navigator.getInstalledRelatedApps is not a function

### ISSUE THREAD

**Issue by tharakabimal** [WICG/get-installed-related-apps#6]
Why do I get the following error?
```
Unhandled Rejection (TypeError):navigator.getInstalledRelatedApps is not a function
```

**Comment by marcoscaceres** [comment]
As the error says, the method `navigator.getInstalledRelatedApps()` doesn't exist in whatever browser you are using. You need check:

```js
if("getInstalledRelatedApps" in navigator) {
   // then... you can call navigator.getInstalledRelatedApps()
   const result = navigator.getInstalledRelatedApps();
}
```

**Comment by tharakabimal** [comment]
Yeah that makes sense but this [article](https://developers.google.com/web/updates/2017/04/getinstalledrelatedapps) says that `getInstalledRelatedApps()` was introduced in `Chrome 59`, and I'm using `Chrome 64`.

**Comment by marcoscaceres** [comment]
right, but it might only be on Chrome for Mobile. The API might not be exposed on Desktop browsers.

**Comment by tharakabimal** [comment]
Yes, I am trying this on Chrome for Mobile 😞

**Comment by marcoscaceres** [comment]
@mgiuca, any ideas? Did `getInstalledRelatedApps()` get removed or maybe behind a flag?

**Comment by tharakabimal** [comment]
Yes @marcoscaceres this is behind a flag. So I assume it's not safe to use this in production. Is there another way that you know of to achieve this?

**Comment by mgiuca** [comment]
It was naturally removed when the origin trial ended, though still available behind a flag.

Note that we are currently deciding whether to proceed with this API, but it looks like we will be replacing it with something simpler (probably a manifest flag), as I discussed in December with @marcoscaceres .

**Comment by tharakabimal** [comment]
@mgiuca is there's a way to detect if my native app is installed without using this API? I'm new to this so please bare with me.

**Comment by dpolyakov** [comment]
same problem:
`
appCodeName: "Mozilla"
appName: "Netscape"
appVersion: "5.0 (Linux; Android 8.0.0; ONEPLUS A3003) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.111 Mobile Safari/537.36"
`

**Comment by tushar004** [comment]
> same problem:
> 
> ```
> appCodeName: "Mozilla"
> appName: "Netscape"
> appVersion: "5.0 (Linux; Android 8.0.0; ONEPLUS A3003) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.111 Mobile Safari/537.36"
> ```



> Why do I get the following error
> 
> ```
> Unhandled Rejection (TypeError):navigator.getInstalledRelatedApps is not a function
> ```


You can use the below code, it's working.
 const fun = navigator['getInstalledRelatedApps'];
listOfInstalledApps = await fun.call(navigator);

**Comment by ishammansoor** [comment]
Method getInstalledRelatedApps() is available only over https.

**Comment by mansoorebrahim** [comment]
Method getInstalledRelatedApps() is available only over https.
